name: Build and Analyze

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Echo Sonar URL to debug
        run: echo ${{ secrets.SONAR_HOST_URL }}

      - name: Run curl command to check SonarQube connection
        run: |
          curl -v ${{ secrets.SONAR_HOST_URL }}/
