name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      # Step 2: Test connection to SonarQube server (optional but useful for debugging)
      - name: Test SonarQube server access
        run: |
          curl -v ${SONAR_HOST_URL}/

      # Step 3: Run SonarQube scan action
      - uses: sonarsource/sonarqube-scan-action@v3
        with:
          projectBaseDir: .
          args: "-X -Dsonar.web.timeout=600"  # Enable debug logging and increase timeout
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Optional: Fail the job if Quality Gate is red (uncomment if required)
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
